-- Comprehensive Test Data with All Property Fields
-- This script creates detailed properties with realistic data for all fields
SET NOCOUNT ON;
USE property_manager_db;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    -- Get owner IDs
    DECLARE @owner1_id INT = (SELECT id FROM dbo.users WHERE email = 'owner1@example.com');
    DECLARE @owner_id INT = (SELECT id FROM dbo.users WHERE email = 'owner@example.com');

    -- If owners don't exist, use any owner
    IF @owner1_id IS NULL
        SET @owner1_id = (SELECT TOP 1 id FROM dbo.users WHERE role = 'owner');
    IF @owner_id IS NULL
        SET @owner_id = @owner1_id;

    -- Delete existing test properties to refresh
    DELETE FROM dbo.properties WHERE property_code LIKE 'PROP-%';

    -- Property 1: Luxury Apartment
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description, 
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id, 
        'Luxury Downtown Apartment with City Views',
        'PROP-001',
        'Modern 3-bedroom apartment in the heart of downtown with stunning city skyline views. Features include hardwood floors, granite countertops, stainless steel appliances, and floor-to-ceiling windows. Walking distance to shopping, dining, and entertainment.',
        '1234 Main Street, Downtown',
        '1234 Main Street',
        'Los Angeles',
        'California',
        '90001',
        'USA',
        'Apartment',
        'Available',
        3,
        2.5,
        1800.00,
        15,
        25,
        'Furnished',
        '2 covered parking spaces',
        '2 balconies',
        'North-East',
        3,
        3500.00,
        3500.00,
        7000.00,
        7000.00,
        0.12,
        89.99,
        75.00,
        250.00,
        45.00,
        1,
        1,
        'CCTV, Security Guard 24/7, Secure Entry',
        1,
        'AT&T Fiber 1Gbps',
        'John Anderson',
        '+1-555-0101',
        GETDATE(),
        'Minimum 12 months lease, 60 days notice required',
        DATEADD(DAY, 15, GETDATE()),
        GETDATE()
    );

    -- Property 2: Modern Townhouse
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id,
        'Modern 4BR Townhouse with Private Garden',
        'PROP-002',
        'Spacious 4-bedroom townhouse featuring an open floor plan, gourmet kitchen with island seating, master suite with walk-in closet, and private backyard garden perfect for entertaining.',
        '5678 Oak Avenue, Suburbs',
        '5678 Oak Avenue',
        'San Francisco',
        'California',
        '94102',
        'USA',
        'Townhouse',
        'Occupied',
        4,
        3.0,
        2400.00,
        NULL,
        3,
        'Semi-Furnished',
        '2 garage spaces + driveway',
        '1 balcony',
        'South',
        2,
        4200.00,
        4200.00,
        8400.00,
        8400.00,
        0.11,
        79.99,
        85.00,
        150.00,
        55.00,
        0,
        1,
        'CCTV, Smart Door Locks',
        1,
        'Comcast Xfinity 500Mbps',
        'Sarah Mitchell',
        '+1-555-0102',
        DATEADD(DAY, -90, GETDATE()),
        'Minimum 12 months lease, 30 days notice',
        DATEADD(DAY, -60, GETDATE()),
        DATEADD(DAY, -90, GETDATE())
    );

    -- Property 3: Cozy Studio
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner_id,
        'Cozy Studio Near University Campus',
        'PROP-003',
        'Perfect for students or young professionals! This efficient studio features a murphy bed, compact kitchen, and excellent natural lighting. Just minutes from campus and public transit.',
        '789 College Street, University District',
        '789 College Street',
        'Seattle',
        'Washington',
        '98101',
        'USA',
        'Studio',
        'Available',
        0,
        1.0,
        550.00,
        3,
        8,
        'Furnished',
        'Street parking',
        'No',
        'East',
        5,
        1350.00,
        1350.00,
        1350.00,
        1350.00,
        0.10,
        49.99,
        40.00,
        75.00,
        0.00,
        1,
        0,
        'Secure Entry, Well-lit',
        0,
        'CenturyLink 100Mbps',
        'Michael Chen',
        '+1-555-0103',
        GETDATE(),
        'Minimum 6 months, flexible terms',
        GETDATE(),
        GETDATE()
    );

    -- Property 4: Luxury Villa
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id,
        'Executive Villa with Pool & Smart Home',
        'PROP-004',
        'Stunning 5-bedroom executive villa with private pool, home theater, wine cellar, and full smart home automation. Gated community with 24/7 security. High-end finishes throughout.',
        '1 Executive Lane, Beverly Hills',
        '1 Executive Lane',
        'Los Angeles',
        'California',
        '90210',
        'USA',
        'Villa',
        'Available',
        5,
        4.5,
        5500.00,
        NULL,
        2,
        'Furnished',
        '4 car garage + guest parking',
        '3 balconies + terrace',
        'South-West',
        1,
        12500.00,
        12500.00,
        25000.00,
        25000.00,
        0.13,
        199.99,
        120.00,
        500.00,
        100.00,
        0,
        1,
        'CCTV, Armed Security, Gated Entry, Smart Locks',
        1,
        'Google Fiber 2Gbps',
        'Robert Williams',
        '+1-555-0104',
        GETDATE(),
        'Minimum 12 months, background check required',
        DATEADD(DAY, 30, GETDATE()),
        GETDATE()
    );

    -- Property 5: Commercial Office Space
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner_id,
        'Premium Office Space - Downtown Business District',
        'PROP-005',
        'Class-A office space in prime downtown location. Features include conference rooms, reception area, private offices, and open workspace. Ready for immediate occupancy.',
        '2500 Business Plaza, Suite 800',
        '2500 Business Plaza',
        'New York',
        'New York',
        '10001',
        'USA',
        'Commercial',
        'Available',
        0,
        3.0,
        3200.00,
        8,
        40,
        'Unfurnished',
        'Dedicated parking for 10 vehicles',
        'No',
        'North',
        7,
        8500.00,
        8500.00,
        17000.00,
        17000.00,
        0.15,
        299.99,
        150.00,
        800.00,
        0.00,
        1,
        1,
        'CCTV, Card Access, Security Desk',
        0,
        'Verizon Fios Business 1Gbps',
        'Corporate Properties LLC',
        '+1-555-0105',
        GETDATE(),
        'Minimum 24 months commercial lease',
        DATEADD(DAY, 7, GETDATE()),
        GETDATE()
    );

    -- Property 6: Family House
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id,
        'Charming Family House in Quiet Neighborhood',
        'PROP-006',
        'Beautiful 3-bedroom family house with large backyard, updated kitchen, hardwood floors throughout. Perfect for families with children. Excellent school district.',
        '456 Maple Drive, Residential',
        '456 Maple Drive',
        'Austin',
        'Texas',
        '78701',
        'USA',
        'House',
        'Under Maintenance',
        3,
        2.0,
        2100.00,
        NULL,
        2,
        'Semi-Furnished',
        '2 car garage',
        '1 balcony',
        'West',
        15,
        2800.00,
        2800.00,
        5600.00,
        5600.00,
        0.09,
        69.99,
        60.00,
        100.00,
        40.00,
        0,
        0,
        'Neighborhood Watch, Alarm System',
        1,
        'Spectrum 400Mbps',
        'Jennifer Davis',
        '+1-555-0106',
        DATEADD(DAY, -15, GETDATE()),
        'Minimum 12 months, pets allowed with deposit',
        DATEADD(DAY, 45, GETDATE()),
        DATEADD(DAY, -15, GETDATE())
    );

    -- Property 7: Modern Condo
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner_id,
        'Waterfront Condo with Marina Views',
        'PROP-007',
        '2-bedroom luxury condo overlooking the marina. Floor-to-ceiling windows, modern appliances, spa-like bathrooms. Building amenities include pool, gym, and concierge service.',
        '888 Harbor Boulevard, Unit 1205',
        '888 Harbor Boulevard',
        'Miami',
        'Florida',
        '33101',
        'USA',
        'Condo',
        'Occupied',
        2,
        2.0,
        1400.00,
        12,
        20,
        'Furnished',
        '1 assigned + guest parking',
        '1 large balcony',
        'East',
        4,
        3200.00,
        3200.00,
        6400.00,
        6400.00,
        0.11,
        79.99,
        55.00,
        350.00,
        35.00,
        1,
        1,
        'CCTV, Concierge, Secure Parking',
        0,
        'Xfinity 600Mbps',
        'Marina Properties Inc',
        '+1-555-0107',
        DATEADD(DAY, -120, GETDATE()),
        'Minimum 12 months lease',
        DATEADD(DAY, -90, GETDATE()),
        DATEADD(DAY, -120, GETDATE())
    );

    -- Property 8: Affordable Flat
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id,
        'Affordable 2BR Flat - Great Starter Home',
        'PROP-008',
        'Clean and well-maintained 2-bedroom flat perfect for young couples or roommates. Updated kitchen and bathroom. Close to public transportation and shopping.',
        '321 Budget Street, Apt 4B',
        '321 Budget Street',
        'Chicago',
        'Illinois',
        '60601',
        'USA',
        'Flat',
        'Available',
        2,
        1.0,
        950.00,
        4,
        6,
        'Unfurnished',
        'Street parking available',
        'Small balcony',
        'North',
        12,
        1600.00,
        1600.00,
        1600.00,
        1600.00,
        0.10,
        45.00,
        35.00,
        50.00,
        25.00,
        0,
        0,
        'Secure Entry',
        0,
        'Spectrum Basic 200Mbps',
        'Budget Rentals LLC',
        '+1-555-0108',
        GETDATE(),
        'Minimum 6 months, month-to-month after',
        DATEADD(DAY, 10, GETDATE()),
        GETDATE()
    );

    -- Property 9: Single Room
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner_id,
        'Private Room in Shared House - All Utilities Included',
        'PROP-009',
        'Private furnished room in clean, quiet shared house. Shared kitchen and living areas. All utilities and internet included in rent. Perfect for students or working professionals.',
        '999 Shared Living Lane',
        '999 Shared Living Lane',
        'Portland',
        'Oregon',
        '97201',
        'USA',
        'Room',
        'Available',
        1,
        0.5,
        180.00,
        2,
        2,
        'Furnished',
        'Street parking',
        'No',
        'South-East',
        8,
        850.00,
        850.00,
        850.00,
        850.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0.00,
        0,
        0,
        'Locked entry, Quiet hours enforced',
        1,
        'Included in rent',
        'Room Share Homes',
        '+1-555-0109',
        GETDATE(),
        'Month-to-month, 30 days notice',
        GETDATE(),
        GETDATE()
    );

    -- Property 10: Penthouse
    INSERT INTO dbo.properties (
        owner_id, title, property_code, description,
        address, street, city, state, zip_code, country,
        property_type, status, bedrooms, bathrooms, area,
        floor_number, total_floors, furnishing_type, parking_space, balcony,
        facing_direction, age_of_property,
        monthly_rent, rent_amount, security_deposit, deposit_amount,
        electricity_rate, internet_rate, water_bill, maintenance_charges, gas_charges,
        elevator, gym_pool_clubhouse, security_features, garden_park_access, internet_provider,
        owner_name, owner_contact, listing_date, lease_terms_default, available_from, created_at
    ) VALUES (
        @owner1_id,
        'Exclusive Penthouse - Panoramic City & Ocean Views',
        'PROP-010',
        'Ultra-luxury penthouse spanning the entire top floor. 4 bedrooms, 5 bathrooms, private elevator, rooftop terrace with infinity pool, home automation, chef''s kitchen, and 360-degree views.',
        '100 Sky Tower, Penthouse',
        '100 Sky Tower',
        'San Diego',
        'California',
        '92101',
        'USA',
        'Apartment',
        'Available',
        4,
        5.0,
        6800.00,
        45,
        45,
        'Furnished',
        'Private garage - 3 spaces',
        'Rooftop terrace',
        'North-West',
        2,
        18500.00,
        18500.00,
        37000.00,
        37000.00,
        0.14,
        249.99,
        150.00,
        1200.00,
        80.00,
        1,
        1,
        'Private Elevator, CCTV, Biometric Access, 24/7 Concierge',
        1,
        'Google Fiber 5Gbps',
        'Premium Properties Group',
        '+1-555-0110',
        GETDATE(),
        'Minimum 24 months, executive lease',
        DATEADD(DAY, 60, GETDATE()),
        GETDATE()
    );

    COMMIT TRANSACTION;
    PRINT 'Successfully inserted 10 comprehensive properties with all fields populated.';
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'Error occurred: ' + ERROR_MESSAGE();
    THROW;
END CATCH;
GO
